# This is a basic workflow to help you get started with Actions

name: azure bicep deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Storage-Account-Azure-Build:
    name: 'AZ Storage Bicep Build'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Login into Azure with Rbac
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }} 
          
      - name: az bicep deploy
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
            az deployment group create --what-if --resource-group APIMTesting --template-file ./storage_account.bicep
            
  Storage-Account-Azure-Deployment:
    name: 'AZ Storage Bicep Deploy'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [Storage-Account-Azure-Build]
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Login into Azure with Rbac
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }} 
          
      - name: az bicep deploy
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
            az deployment group create --resource-group APIMTesting --template-file ./storage_account.bicep
